### ISSUE TITLE
Windows docker does not start in Windows Anaconda

### ISSUE THREAD

**Issue by chdeb** [vatlab/sos-notebook#100]
Hi,

I'm running Anaconda 1.8.7 and Docker 18.03.1-ce on Windows (version 1803 - 64-bit), both work fine on their own. But when running a script from Jupyter notebook that requires the docker, it fails.
I get the following error code:

%sosrun mixOmics
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
script_627761264244055517 in <module>
      
----> """, docker_image='vibbioinfocore/rocker_conda_data_integration')

AttributeError: module 'os' has no attribute 'getuid'

**Comment by vibbits** [comment]
additionally, we tried to run sos-notebook within the Linux Ubuntu 18.04 subsystem on Windows 10. with the help of this [blog](https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4) we managed to run dockers on the WSL command line.
Furthermore, we are able to run sos-notebook/jupyter and simple operations in the jupyter notebook.
unfortunately, the docker is started (according to docker log) but no commands are executed.

this is the snippet of the mixOmics cell.
```
[mixOmics]
input: fileOmics_1, fileOmics_2, fileOmics_3, fileOmics_4
parameter: nameOmics_1 = "datExpr"
parameter: nameOmics_2 = "metabolites"
parameter: nameOmics_3 = "proteins"
parameter: nameOmics_4 = ""
parameter: sampleData = "treatment.csv" 
parameter: annotationGenes = "genesAnno.csv"

# we can only integrate two different types of data - in our case it is expression data and metabolites

#to do: create folders and add output variables accordingly

R: docker_image='vibbioinfocore/rocker_conda_data_integration', expand  = '${ }'
#=====================================================================================
#
#  Part 1: Read data and transform the data in the correct format
#
#=====================================================================================
library(mixOmics)
# set working directory like:
#setwd("/home/usr/Oren/MixOmics")
getwd()
dir.create("mixOmics")
``` 
we will experiment a bit further whether it is possible to run our docker from the WSL command line with a script e.g. 
```
docker run --rm --security-opt label:disable  -v /home:/home -v /tmp:/tmp -v /home/alex/OmicsIntegrationToolkit/.sos/docker_run_5433.R:/var/lib/sos/docker_run_5433.R    -t -P -w=/home/alex/OmicsIntegrationToolkit/InputFiles -u 1000:1000 vibbioinfocore/rocker_conda_data_integration Rscript /var/lib/sos/docker_run_5433.R
```

**Comment by vibbits** [comment]
I just found: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly - hopefully the suggested changes work out to make this setup work!

**Comment by BoPeng** [comment]
Yes, `os.getuid()` is only available for mac/linux. We did not pay attention to docker on windows because it was not in a usable state the last time we checked, and none of us uses windows OS for work. I will try to install docker on a windows machine and check.

BTW, in case you do not know, https://vatlab.github.io/sos-docs/doc/tutorials/SoS_Docker_Guide.html is our latest documentation on docker.

**Comment by BoPeng** [comment]
I cannot test now but I have blindly removed the `-u` option under windows. Could you please check if it works for you? If it does not work, you can run the workflow in dryrun mode (`%run -n`) to get a docker command, modify it and see what options need to be added/modified.
